### ISSUE TITLE
主板自带的Wi-Fi和蓝牙可以驱动吗？

### ISSUE THREAD

**Issue by cloudsben** [qinkangdeid/z370n-wifi-hackintosh#1]
主板自带的Wi-Fi和蓝牙可以驱动吗？还是说需要买其他的Wi-Fi搞定？

**Comment by qinkangdeid** [comment]
自带的不能 需要更换

Ben <notifications@github.com> 于 2018年7月5日周四 08:32写道：

**Comment by cloudsben** [comment]
OK，谢谢了，已经放弃使用黑苹果了，这主板支持一般

**Comment by deepure** [comment]
楼主是拆了主板上的无线网卡，还是添加了一个943602cs？
