### ISSUE TITLE
After sleep, something wrong 

### ISSUE THREAD

**Issue by smail2133** [qinkangdeid/z370n-wifi-hackintosh#2]
![screen shot 2018-08-25 at 3 42 14 pm](https://user-images.githubusercontent.com/5464497/44618399-a22c7100-a87d-11e8-9e26-5da5a4e2997c.png)

**Comment by yangbe** [comment]
![image](https://user-images.githubusercontent.com/9880101/46580708-68de4800-ca5c-11e8-8b5f-5d60ccde31e8.png)
