### ISSUE TITLE
你好，请问这个efi文件夹。各种驱动完善吗？

### ISSUE THREAD

**Issue by a4562248** [qinkangdeid/z370n-wifi-hackintosh#20]

**Comment by a4562248** [comment]
我的配置和你这个几乎一样的。也是z370n主板

**Comment by qinkangdeid** [comment]
目前都是可以正常使用  各大驱动都完善了... 没什么问题

**Comment by a4562248** [comment]
> 目前都是可以正常使用 各大驱动都完善了... 没什么问题

哇，这么快就回复啦，谢谢大佬。提个小建议，那个 制作黑苹果U盘启动器 的文章，还可以接着加上把efi文件从U盘转移到系统硬盘的步骤哟。  这样就更完美啦

**Comment by qinkangdeid** [comment]
> > 目前都是可以正常使用 各大驱动都完善了... 没什么问题
> 
> 哇，这么快就回复啦，谢谢大佬。提个小建议，那个 制作黑苹果U盘启动器 的文章，还可以接着加上把efi文件从U盘转移到系统硬盘的步骤哟。 这样就更完美啦

这个可以有 已更新了

**Comment by a4562248** [comment]
谢谢啦，使用你的efi文件夹，相同的主板，dw1560网卡。  用黑果小兵的教程安装了网卡驱动。  加了rx570蓝宝石，显卡免驱。几乎完美了。  8700k，超频到4.8g，多核跑分可以3万。  

以上是我的黑果配置。供给网友参考
