### ISSUE TITLE
bios疑问

### ISSUE THREAD

**Issue by JackThinking** [qinkangdeid/z370n-wifi-hackintosh#3]
请问安装前是先升级主板bios到官方的F3嘛，还是你那边diy过的bios呢？

**Comment by qinkangdeid** [comment]
先升级BIOS到F3 然后load diy的

**Comment by yangbe** [comment]
diy过的bios用什么方式load的？？？跟刷bios一样吗？

**Comment by gz0007** [comment]
同问:diy过的bios用什么方式load的？？？跟刷bios一样吗？
