### ISSUE TITLE
USB 3.1 Type C 驱动不了，有线网络接口也只能驱动一个

### ISSUE THREAD

**Issue by yangbe** [qinkangdeid/z370n-wifi-hackintosh#4]

**Comment by qinkangdeid** [comment]
不好意思 TypeC 我没用设备测试   升级了10.14了  试了下 两个有线网口都能用了

**Comment by yangbe** [comment]
![image](https://user-images.githubusercontent.com/9880101/46708591-065e9500-cc72-11e8-849c-0e8da3ee14b9.png)
我现在需要这两个kext才能驱动两个有线网口。

**Comment by qinkangdeid** [comment]
嗯 我在10.14里加了
