### ISSUE TITLE
博通蓝牙wifi

### ISSUE THREAD

**Issue by BaoHan** [qinkangdeid/z370n-wifi-hackintosh#45]

**Comment by BaoHan** [comment]
蓝牙接板载 usb 2.0 应该是usb 驱动原因，被屏蔽了。蓝牙无法被正确识别。

**Comment by qinkangdeid** [comment]
定制的SSDT或USBPorts都一排除板载插针的USB2.0口 需要的 你可以自己定制一下

BaoHan <notifications@github.com> 于2019年4月28日周日 上午11:06写道：
