### ISSUE TITLE
使用EFI无法进去10.14.4安装界面

### ISSUE THREAD

**Issue by szk5043** [qinkangdeid/z370n-wifi-hackintosh#50]
使用master分支的EFI无法进去10.14.4安装界面

**Comment by szk5043** [comment]
#
![微信图片_20190429165944](https://user-images.githubusercontent.com/16665480/56885957-70b91480-6aa0-11e9-89f6-d4aaf2990e9b.jpg)

**Comment by szk5043** [comment]
主板BIOS设置确认无误

**Comment by qinkangdeid** [comment]
把启动U盘插到USB 2.0口 试试

**Comment by qinkangdeid** [comment]
我重新用EFI安装了一次 是可以的
 请如果你的不可以 请更换USB口
或重新检查设置BIOS或检查你的U盘启动器是否可用
