### ISSUE TITLE
DP连接显示器音频无声音输出

### ISSUE THREAD

**Issue by michensy** [qinkangdeid/z370n-wifi-hackintosh#55]
你好，非常感谢，我用了这个EFI成功在 8700 + z370N 平台安装了 10.13.5系统，显示器用的是 Dell U2718QM 4K，目前有个小遗憾，就是通过显卡的 DP接口连接显示器后，耳机插入显示器提供的音频口并没有声音输出，可以赐教一下吗？不胜感激！
![image](https://user-images.githubusercontent.com/30194203/57773723-44152600-774b-11e9-8315-70fba3cc0d38.png)

**Comment by qinkangdeid** [comment]
我的显示器是U2718Q 是可以的
你有没有在`声音`指定输出？
<img width="662" alt="dp" src="https://user-images.githubusercontent.com/17582522/57779757-55652f00-7759-11e9-8b6f-89f460222c4a.png">

**Comment by xiazidong** [comment]
我的声音输出设置中没有这个选项 很奇怪 淘宝找了三个人没调好，很惆怅

**Comment by qinkangdeid** [comment]
你可以装到10.14.x的 13.x已经很久不动了
