### ISSUE TITLE
GPU的温度和频率在HWMonitor上能否显示？要设置哪些？

### ISSUE THREAD

**Issue by yangbe** [qinkangdeid/z370n-wifi-hackintosh#6]

**Comment by qinkangdeid** [comment]
我没加显卡,你可以看看这个 https://hackintosher.com/guides/hwmonitor-hackintosh-guide/
![image](https://user-images.githubusercontent.com/17582522/50806512-02eeae80-1332-11e9-9784-5738b05f7506.png)
