### ISSUE TITLE
UHD630核显双HDMI屏时，HDMI2的屏会出现闪屏

### ISSUE THREAD

**Issue by isshe** [qinkangdeid/z370n-wifi-hackintosh#60]
之前直接用multibeast整的EFI好像不会闪屏，但是当时的音频没整好。现在音频好了，HDMI出现闪屏。。。

**Comment by qinkangdeid** [comment]
我是DP+HDMI   没连过双HDMI   你可以试着换机型试试

**Comment by isshe** [comment]
> 我是DP+HDMI 没连过双HDMI 你可以试着换机型试试 是两个屏幕都闪吗？
DP+HDMI也会闪，是HDMI2.0接口的问题，只要接了这个，睡眠起来以后，就有几率闪屏。

**Comment by qinkangdeid** [comment]
> > 我是DP+HDMI 没连过双HDMI 你可以试着换机型试试 是两个屏幕都闪吗？
> 
> DP+HDMI也会闪，是HDMI2.0接口的问题，只要接了这个，睡眠起来以后，就有几率闪屏。

你的是两个高分屏？我一个4k+1080P没问题 有空我试试两个HDMI

**Comment by isshe** [comment]
> > > 我是DP+HDMI 没连过双HDMI 你可以试着换机型试试 是两个屏幕都闪吗？
> > 
> > 
> > DP+HDMI也会闪，是HDMI2.0接口的问题，只要接了这个，睡眠起来以后，就有几率闪屏。
> 
> 你的是两个高分屏？我一个4k+1080P没问题 有空我试试两个HDMI

我是两个1080P的。双屏情况下，HDMI2的接口就很大概率闪屏/花屏。通常是在睡眠唤醒以后出现。
这个目前影响不大，你忙你的就好。感谢共享/维护的EFI。现在我基本都是看你的更新了，自己懒得再搞了，接下来的10.15，期待你的更新。再次感谢。

**Comment by isshe** [comment]
建议：
1. EFI文件夹打包上传，因为github对于空文件夹是不上传的。
2. 其他文件放其他仓库，因为国内github下载超级慢(50KB/s)。（还是说这只是我个人的问题？）

**Comment by qinkangdeid** [comment]
目前我接两个屏幕了，现在来说没问题 没闪屏 正常使用 但是要有点小小的技巧（开机的时候只插HDMI2.0，等待开机完成后，再接上DP，就不会出现有一个屏幕黑屏的情况，具体还不知道为啥，但是这样操作之后双屏是可以用的 没问题）难道还挑线？
<img width="584" alt="moniter" src="https://user-images.githubusercontent.com/17582522/60750833-bcc49000-9fe0-11e9-8342-23af19145a98.png">

**Comment by yinxianwei** [comment]
> 目前我接两个屏幕了，现在来说没问题 没闪屏 正常使用 但是要有点小小的技巧（开机的时候只插HDMI2.0，等待开机完成后，再接上DP，就不会出现有一个屏幕黑屏的情况，具体还不知道为啥，但是这样操作之后双屏是可以用的 没问题）难道还挑线？
> <img alt="moniter" width="584" src="https://user-images.githubusercontent.com/17582522/60750833-bcc49000-9fe0-11e9-8342-23af19145a98.png">

我的显示器也是U2718Q，有个问题是睡眠后唤醒慢，在10s左右，如果【显示器睡眠】不启用就正常在3s左右，你有这个问题吗？

**Comment by yyork** [comment]
反馈一下，我用DP单显示器LG UL600 ，睡眠后也会出现闪屏
