### ISSUE TITLE
Gigabyte Z390 I AORUS PRO WIFI 也可以输出双4K吗？

### ISSUE THREAD

**Issue by ChevalierWang** [qinkangdeid/z370n-wifi-hackintosh#64]
很佩服你这个核显带双4K，平时使用卡不卡？

另外，这个主板已经停产了，到处都买不到...tonymacx86推荐的Gigabyte Z390 I AORUS PRO WIFI也可以输出双4K吗？

另外+2，第一张图上桌子上立着的机箱是哪款？

谢谢

**Comment by qinkangdeid** [comment]
1. 平时办公用的 没有任何问题（我工作上没用到需要持续吃显卡的应用）

2. 主板带有有DP和HDMI2.0的都是可以的 你说的这块板是可以双屏4K的
> 显示功能
内建于有显示功能的处理器+MegaChips MCDP2800芯片：
> 1个HDMI插座，可支持至最高4096x2160@60 Hz的分辨率
* 支持HDMI 2.0版本、HDCP 2.2及HDR。
内建于有显示功能的处理器-支持Intel® HD Graphics：
> 1个DisplayPort插座，可支持至最高4096x2304@60 Hz的分辨率
* 支持DisplayPort 1.2版本、HDCP 2.2及HDR。
支持最大共享显示内存至1 GB

3. 机箱是SKTC C01 （散热不太理想 就是样子好看些 😄）

**Comment by ChevalierWang** [comment]
多谢回复。

昨晚上研究发现Gigabyte Z390 I AORUS PRO WIFI的Wi-Fi模块做了阉割，只能支持Intel CNVi接口了，大量的NGFF Wi-Fi网卡都无法替换使用了，遗憾。
> https://www.gigabyte.cn/Motherboard/Z390-I-AORUS-PRO-WIFI-rev-10/sp#sp
> 1个M.2 Socket 1插座仅供Intel® CNVi无线模块使用(CNVI)

又研究了大半天，发现即能支持NGFF网卡接口，又有HDMI2.0的ITX主板，只发现了这一款：
华擎 Z390 Phantom Gaming-ITX/ac

> https://www.asrock.com/mb/Intel/Z390%20Phantom%20Gaming-ITXac/index.cn.asp#Specification
> - 支持 HDMI 2.0, 最大分辨率达 4K x 2K (4096x2160) @ 60Hz
> - 支持 DisplayPort 1.2, 最大分辨率达 4K x 2K (4096x2304) @ 60Hz

这款是不是也可以核显输出双4K呢？

**Comment by qinkangdeid** [comment]
> 多谢回复。
> 
> 昨晚上研究发现Gigabyte Z390 I AORUS PRO WIFI的Wi-Fi模块做了阉割，只能支持Intel CNVi接口了，大量的NGFF Wi-Fi网卡都无法替换使用了，遗憾。 现在发现你这款主板真是绝版了，买都买不到 😂
> 
> > https://www.gigabyte.cn/Motherboard/Z390-I-AORUS-PRO-WIFI-rev-10/sp#sp
> > 1个M.2 Socket 1插座仅供Intel® CNVi无线模块使用(CNVI)
> 
> 又研究了大半天，发现即能支持NGFF网卡接口，又有HDMI2.0的ITX主板，只发现了这一款：
> 华擎 Z390 Phantom Gaming-ITX/ac
> 
> > https://www.asrock.com/mb/Intel/Z390%20Phantom%20Gaming-ITXac/index.cn.asp#Specification
> > 
> > * 支持 HDMI 2.0, 最大分辨率达 4K x 2K (4096x2160) @ 60Hz
> > * 支持 DisplayPort 1.2, 最大分辨率达 4K x 2K (4096x2304) @ 60Hz
> 
> 这款是不是也可以核显输出双4K呢？

可以的
