### ISSUE TITLE
Catalina目前可公开BUG

### ISSUE THREAD

**Issue by isshe** [qinkangdeid/z370n-wifi-hackintosh#66]
* 声卡跪了，只能识别显示器的音频输出。耳机识别不了。
* 蓝牙跪了，这个之前也不稳定，一直没管。这个应该好解。
    * BCM94352z/DW1560
* WIFI启动慢，系统起来后2分钟左右，WIFI才能使用。
* _之前10.14.6用着用着会重启（一天左右），不知道现在还有没有这个问题，可能和显卡有关。（45W的RX560）_

**Comment by a4562248** [comment]
1. 声卡没注意，之前一直用的蓝牙耳机。
2.蓝牙和wifi应该是同一个问题，dw1560的驱动问题。 我从10.14.4刚升级到10.15.2的时候启动比较慢，进入到桌面后也是wifi图标要2分钟左右才能出来，而且蓝牙不可用。 后来到github搜索dw1560，用了其他机型适配的efi的dw1560驱动，wifi和蓝牙都0k了，而且启动速度很快，和10.14.4几乎没区别了。

附上链接，https://github.com/AceInAndroid/Deskmini310-dw1560-hackintosh-EFI
我是把EFI/CLOVER/kexts/Other/ 里面的AirportBrcmFixup.kext， BrcmBluetoothInjector.kext， BrcmFirmwareData.kext， BrcmPatchRAM3.kext。这几个都移动到我efi对应的文件夹了。  重启就突然wifi和蓝牙都ok了。

希望对大伙有所帮助，一路都是靠这位作者提供的教程升级上来的。

**Comment by qinkangdeid** [comment]
> 1. 声卡没注意，之前一直用的蓝牙耳机。
>    2.蓝牙和wifi应该是同一个问题，dw1560的驱动问题。 我从10.14.4刚升级到10.15.2的时候启动比较慢，进入到桌面后也是wifi图标要2分钟左右才能出来，而且蓝牙不可用。 后来到github搜索dw1560，用了其他机型适配的efi的dw1560驱动，wifi和蓝牙都0k了，而且启动速度很快，和10.14.4几乎没区别了。
> 
> 附上链接，https://github.com/AceInAndroid/Deskmini310-dw1560-hackintosh-EFI
> 我是把EFI/CLOVER/kexts/Other/ 里面的AirportBrcmFixup.kext， BrcmBluetoothInjector.kext， BrcmFirmwareData.kext， BrcmPatchRAM3.kext。这几个都移动到我efi对应的文件夹了。 重启就突然wifi和蓝牙都ok了。
> 
> 希望对大伙有所帮助，一路都是靠这位作者提供的教程升级上来的。

感谢🙏 我的是免驱卡 所以里面没有放博通的kext，我开个小文件夹存放一下这些驱动  给需要的人参考下
