### ISSUE TITLE
有人试过 Macs Fan Control 有效吗？

### ISSUE THREAD

**Issue by ChevalierWang** [qinkangdeid/z370n-wifi-hackintosh#70]
温度监控都正常，iStat Menus 和 HWMonitor 显示都正常
Macs Fan Control 无法控制风扇，只要自定义转速，无论输入多少转速，风扇都会满速，而且无法恢复到自动模式

有人试成功过吗？

**Comment by qinkangdeid** [comment]
我没用过这个软件呢 不太清楚
