### ISSUE TITLE
typec口只要插上 无线wifi就断开并且连接不上任何Wi-Fi

### ISSUE THREAD

**Issue by cwr31** [qinkangdeid/z370n-wifi-hackintosh#74]
网卡用的是bcm94360cs2
其他都用的你的efi 没啥区别啊我寻思着

**Comment by qinkangdeid** [comment]
> 网卡用的是bcm94360cs2
> 其他都用的你的efi 没啥区别啊我寻思着

没有typec的设备 我晚点找个插上去看看

**Comment by kdwycz** [comment]
网卡是bcm94360cs2。尝试了下 type-c 没问题
