### ISSUE TITLE
SSDT-UIAC-All-ports-Z370N-W.dsl 怎样使用？

### ISSUE THREAD

**Issue by yangbe** [qinkangdeid/z370n-wifi-hackintosh#9]
这个是用来解决什么问题的？？
---
![image](https://user-images.githubusercontent.com/9880101/50380809-084fc600-06af-11e9-8ee9-f1a1c8bc391f.png)

---

下面这里的USB补丁呢？升级到14.2后可以不用USB补丁？？
---
![image](https://user-images.githubusercontent.com/9880101/50380815-32a18380-06af-11e9-8925-f0b7f55b750f.png)

**Comment by coolemiao** [comment]
release里面没有这个文件, 请问是不需要使用这个文件吗, 现在推荐使用release版本, 还是master呢. 目录中的hackintosh_config能简单说下怎么使用吗, 小白问题有点多, 见谅, 谢谢

**Comment by qinkangdeid** [comment]
> release里面没有这个文件, 请问是不需要使用这个文件吗, 现在推荐使用release版本, 还是master呢. 目录中的hackintosh_config能简单说下怎么使用吗, 小白问题有点多, 见谅, 谢谢

有时间我写点说明吧

**Comment by yangbe** [comment]
@qinkangdeid  用了你的那个SSDT补丁后，前置的两个USB使用不了，有教程可以让我看看怎样修改吗？

**Comment by qinkangdeid** [comment]
前面板的USB我屏蔽了,SSDT的方式保证端口在15个以内

教程你可以参考这个：https://www.tonymacx86.com/threads/guide-creating-a-custom-ssdt-for-usbinjectall-kext.211311/

这块板子的USB端口我都标记下来了，你只需要使用`MaciASL`修改`/EFI/CLOVER/ACPI/patched/SSDT-UIAC.aml`文件将你想要开放的端口写在SSDT文件里就行：

MaciASL下载地址：<https://bitbucket.org/RehabMan/os-x-maciasl-patchmatic/downloads>/

> UsbConnector对应关系：
>
> USB2.0 对应 0
>
> USB3.0 对应 3 （USB3.0兼容USB2.0，所以一个USB3.0接口需要两个端口，如果不想要USB2.0可以不加上USB2.0的端口）
>
> 其他内建USB对应 255
>
> TYPC 对应:
>
> 如果USB-C在两个方向上使用相同的SSxx，UsbConnector = 9
>
>  如果USB-C在每个方向使用不同的SSxx，UsbConnector = 10

# Z370WIFI USB孔位

- 网卡下面两个USB
  - SS04 网卡下第一个
  - HS04 2.0
  - SS03 第二个
  - HS03 2.0
- 四排USB从下往上
  - SS07 3.0
  - HS07 2.0
  - SS08
  - HS08 2.0
  - SS05
  - HS05 2.0
  - SS06
  - HS06 2.0
- 扩展USB3.0
  - SS01 上 （3.0）
  - HS01 上 （2.0）
  - SS02 下 （3.0）
  - HS02 下（2.0）
- USB2.0(插针)
  - HS12 上
  - HS11 下
- Type-C
  - HS09
- Bluetooth
  - HS10
