### ISSUE TITLE
请问一下，你的主板BIOS解锁CFG Lock了么，想拿过来直接用

### ISSUE THREAD

**Issue by zhangdongpo** [qinkangdeid/z370n-wifi-hackintosh#93]

**Comment by wjswjw** [comment]
> _没有提供描述。_

我是直接刷了F10的BIOS，我看网上说F10不需要解锁CFG

**Comment by qinkangdeid** [comment]
> > _没有提供描述。_
> 
> 我是直接刷了F10的BIOS，我看网上说F10不需要解锁CFG

F10不需要解锁CFG也可以使用 所以你还停留在F10的话 可以不用管CFG 不解锁 F10以后的BIOS不解锁就开不了机了

**Comment by zhangdongpo** [comment]
> > > _没有提供描述。_
> > 
> > 
> > 我是直接刷了F10的BIOS，我看网上说F10不需要解锁CFG
> 
> F10不需要解锁CFG也可以使用 所以你还停留在F10的话 可以不用管CFG 不解锁 F10以后的BIOS不解锁就开不了机了

我的还是F3，还没升级。我在想升级到F10还是升级到最新的。升级到最新的需要手动解锁CFG么？

**Comment by Nemezus** [comment]
What is CFG?
I have F10 BIOS and plan to upgrade to F13

**Comment by zhangdongpo** [comment]
> What is CFG?
> I have F10 BIOS and plan to upgrade to F13

https://www.zdynb.cn/2020/cha-kan-zhu-ban-cfg-lock-zhuang-tai.html

**Comment by Nemezus** [comment]
<key>KernelPm</key>
		<true/>
In your config I see KernelPm=True, it does not helps?

**Comment by kdwycz** [comment]
> 我的还是F3，还没升级。我在想升级到F10还是升级到最新的。升级到最新的需要手动解锁CFG么？

可以直接升级 F13 的

**Comment by zhangdongpo** [comment]
> > 我的还是F3，还没升级。我在想升级到F10还是升级到最新的。升级到最新的需要手动解锁CFG么？
> 
> 可以直接升级 F13 的

我升级了F13的，现在用OpenCore引导的，长时间睡眠唤醒后会显示报错然后重新启动。你有这个问题么

**Comment by zhangdongpo** [comment]
> > 我的还是F3，还没升级。我在想升级到F10还是升级到最新的。升级到最新的需要手动解锁CFG么？
> 
> 可以直接升级 F13 的

你好，我的升级了F13，现在有个问题就是长时间睡眠后唤醒系统会显示有错误直接进行重启。你的BIOS版本是F13么，有这个问题么？

**Comment by qinkangdeid** [comment]
BIOS文件：https://github.com/qinkangdeid/z370n-wifi-hackintosh-attachment
