### ISSUE TITLE
z370 不是自带nvram的吗 为啥还使用了EmuVariableUefi.efi

### ISSUE THREAD

**Issue by wjswjw** [qinkangdeid/z370n-wifi-hackintosh#94]
因为EmuVariableUefi.efi导致我四叶草引导不能记住上次的引导项，所以去掉了EmuVariableUefi.efi就一切正常了。另外Z370N不是自带EmuVariableUefi.efi 为什么楼主还使用了EmuVariableUefi.efi这个呢 不知道去掉有没有什么影响

**Comment by wjswjw** [comment]
对了在补充一个问题。单显示器使用HDMI1.4接口开机白苹果LOGO过后不显示。使用2.0HDMI接口没有总是。我试了另外一个人的EFI没有发生这个总是。我提供一下链接 楼主可以看下是哪里的原因。更加的完善这个EFI吗  https://github.com/yangbe/z370n-wifi-vega64

**Comment by qinkangdeid** [comment]
> 因为EmuVariableUefi.efi导致我四叶草引导不能记住上次的引导项，所以去掉了EmuVariableUefi.efi就一切正常了。另外Z370N不是自带EmuVariableUefi.efi 为什么楼主还使用了EmuVariableUefi.efi这个呢 不知道去掉有没有什么影响

z370原生支持nvram   是不需要`EmuVariableUefi.efi`的 可以去掉

**Comment by qinkangdeid** [comment]
> 对了在补充一个问题。单显示器使用HDMI1.4接口开机白苹果LOGO过后不显示。使用2.0HDMI接口没有总是。我试了另外一个人的EFI没有发生这个总是。我提供一下链接 楼主可以看下是哪里的原因。更加的完善这个EFI吗 https://github.com/yangbe/z370n-wifi-vega64

好哒🙏 有时间我对比下  我是改了帧缓冲 为了使用双屏4K

**Comment by Nemezus** [comment]
Are you sure that Z370N-WiFI has native NVRAM support?

**Comment by wjswjw** [comment]
> > 因为EmuVariableUefi.efi导致我四叶草引导不能记住上次的引导项，所以去掉了EmuVariableUefi.efi就一切正常了。另外Z370N不是自带EmuVariableUefi.efi为什么楼主还使用了EmuVariableUefi.efi这个呢不知道去掉有没有什么影响
> 
> z370原生支持nvram是不需要`EmuVariableUefi.efi`的可以去掉

好的 感谢回复，这主板是原生支持NVRAM，的确去掉EmuVariableUefi.efi 没有任务影响 而反修复了开机引导记住上次引导项的问题，我也是看楼主一直更新，所以想在楼主的EFI内，可以精简一些不需要的文件

**Comment by qinkangdeid** [comment]
> Are you sure that Z370N-WiFI has native NVRAM support?

Yes.

**Comment by wjswjw** [comment]
> Are you sure that Z370N-WiFI has native NVRAM support?

对的 当然支持了 大部分z370都支持
