### ISSUE TITLE
前置USB有点问题，求大佬帮忙~

### ISSUE THREAD

**Issue by Gantios** [qinkangdeid/z370n-wifi-hackintosh#96]
前置2个USB，却没法使用，后置面板上6个USB都是正常的，不知道你们有没有遇到过?

**Comment by wjswjw** [comment]
> 最初2个USB，却没法使用，后置面板上6个USB都是正常的，不知道你们有没有遇到过？

博主已经说明了  前置的需要自己USB定制的  也提供了教程
