### ISSUE TITLE
楼主 引导界面我会在技嘉LOGO停5秒左右

### ISSUE THREAD

**Issue by wjswjw** [qinkangdeid/z370n-wifi-hackintosh#97]
你的会这样吗 如果是选择从windows硬盘引导秒进  如果是用四叶草引导就会在技嘉LOGO停5秒好久啊  另外没有找到你上传的BIOS文件

**Comment by qinkangdeid** [comment]
这个还真没注意到 买来就装了macOS 应该不影响使用  BIOS文件：https://github.com/qinkangdeid/z370n-wifi-hackintosh-attachment
