### ISSUE TITLE
烦请帮忙解决一下独显问题

### ISSUE THREAD

**Issue by newger149** [qinkangdeid/z370n-wifi-hackintosh#98]
感谢大神的付出，用上一切都挺好。最近入了蓝宝石的公版rx5700，bios进行了如下设置，结果本efi白苹果进度条快跑完时，直接重启了，连错误跑码都看不到，不明白是哪里出了问题。

1.   保存并退出→加载优化的默认值
2.   MIT→高级内存设置极限内存配置文件（XMP）：配置文件1
3.   BIOS→快速启动：禁用
4.   BIOS→LAN PXE引导选项ROM：已禁用
5.   BIOS→存储启动选项控制：UEFI
6.   外围设备→可信计算→安全设备支持：禁用
7.   外围设备→网络堆栈配置→网络堆栈：禁用
9.   外围设备→USB配置→XHCI切换：启用
10.   芯片组→Vt-d：禁用
11.   芯片组→局域网唤醒启用：禁用
12.   芯片组→IOAPIC 24-119条目：启用

**Comment by qinkangdeid** [comment]
没有加过独显使用过呢  你可以参考下这个教程https://github.com/yangbe/z370n-wifi-vega64
